/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vista;

import com.controlador.ControladorAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author river
 */
public class MenuAdmin extends javax.swing.JFrame {
    private ControladorAdmin controlador;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }
     public MenuAdmin(ControladorAdmin controlador) {
        this.controlador = controlador;
        initComponents();
        configurarEventos();
    }

    private void configurarEventos() {
        jButton1.addActionListener(e -> {
            FormularioDocente formDocente = new FormularioDocente(this, controlador);
            formDocente.setLocationRelativeTo(this); 
            formDocente.setVisible(true);
        });
        jButton2.addActionListener(e -> {
            FormularioEstudiante formEstudiante = new FormularioEstudiante(this, controlador);
            formEstudiante.setLocationRelativeTo(this); 
            formEstudiante.setVisible(true); 
        });
        btnCerrarSesion.addActionListener(e -> {
            Principal principal = new Principal(); 
            principal.setVisible(true);
            principal.setLocationRelativeTo(null);
            this.dispose(); 
        });
        btnCrearCurso.addActionListener(e -> {
            FormularioCurso formCurso = new FormularioCurso(this, controlador);
            formCurso.setLocationRelativeTo(this); 
            formCurso.setVisible(true); 
         });
        btnListarDocentes.addActionListener(e -> {
            String listaDocentes = controlador.listarTodosLosProfesores(); 
            JOptionPane.showMessageDialog(this, listaDocentes, "Lista de Docentes", JOptionPane.INFORMATION_MESSAGE);
        });
        btnListarEstudiantes.addActionListener(e -> {
                String listaEstudiantes = controlador.listarTodosLosEstudiantes(); 
                JOptionPane.showMessageDialog(this, listaEstudiantes, "Lista de Estudiantes", JOptionPane.INFORMATION_MESSAGE);
         });           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnListarDocentes = new javax.swing.JButton();
        btnListarEstudiantes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCrearCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENU ADMIN");

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setText("GESTION COLEGIO");

        jButton1.setText("Agregar Docente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Estudiante");

        btnListarDocentes.setText("Listar Docente");

        btnListarEstudiantes.setText("Listar Estudiante");

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCrearCurso.setText("Crear curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarSesion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnListarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListarDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(btnCrearCurso)))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListarDocentes)
                            .addComponent(btnCrearCurso))
                        .addGap(18, 18, 18)
                        .addComponent(btnListarEstudiantes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearCurso;
    private javax.swing.JButton btnListarDocentes;
    private javax.swing.JButton btnListarEstudiantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration                   
}

