/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vista;

import com.controlador.ControladorAdmin;
import com.controlador.ControladorDocente;
import com.controlador.ControladorEstudiante;
import com.modelo.Asignatura;
import com.modelo.Colegio;
import com.modelo.Curso;
import com.modelo.Persona;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author river
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal2
     */
private Colegio colegio;
    private ControladorAdmin controladorAdmin;

    /**
     * Creates new form Principal2
     */
    public Principal() {
        this.colegio = Colegio.getInstance("Mi Colegio"); //
      
        this.controladorAdmin = new ControladorAdmin(this.colegio); //

        initComponents(); 
        configurarEventos(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();
        rolComboBox = new javax.swing.JComboBox<>();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setText("GESTION COLEGIO");

        rolLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rolLabel.setText("SELECCIONA TU ROL:");

        rolComboBox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "DOCENTE", "ESTUDIANTE" }));
        rolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolComboBoxActionPerformed(evt);
            }
        });

        btnContinue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContinue.setText("CONTINUAR");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnContinue)
                .addGap(292, 292, 292))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(rolLabel)
                        .addGap(28, 28, 28)
                        .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(titulo)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titulo)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolLabel)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnContinue)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
     private void configurarEventos() {
        btnContinue.addActionListener(e -> {
            String rolSeleccionado = (String) rolComboBox.getSelectedItem();
            int codigo = -1; 
            
            try {
                if (!"ADMIN".equals(rolSeleccionado)) {
                    String codigoStr = JOptionPane.showInputDialog(this, "Ingrese su código:");
                    if (codigoStr == null) { 
                        return;
                    }
                    codigo = Integer.parseInt(codigoStr);
                }

                boolean autenticado = false;
             
                if ("ADMIN".equals(rolSeleccionado)) {
                    autenticado = true; 
                } else {
                    autenticado = controladorAdmin.autenticar(codigo, rolSeleccionado.toLowerCase());
                }

                if (autenticado) {
                    JOptionPane.showMessageDialog(this, "Bienvenido " + rolSeleccionado + "!", "Acceso Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose(); 

                    switch (rolSeleccionado) {
                        case "ADMIN":
                            MenuAdmin menuAdmin = new MenuAdmin(controladorAdmin); //
                            menuAdmin.setVisible(true);
                            menuAdmin.setLocationRelativeTo(null);
                            break;
                        /*case "DOCENTE":
                            // Necesitamos pasar el colegio y el código al ControladorDocente
                            ControladorDocente controladorDocente = new ControladorDocente(colegio, codigo); //
                            MenuDocente menuDocente = new MenuDocente(controladorDocente); // Asume MenuDocente tiene constructor con ControladorDocente
                            menuDocente.setVisible(true);
                            menuDocente.setLocationRelativeTo(null);
                            break;
                        case "ESTUDIANTE":
                            // Necesitamos pasar el colegio y el código al ControladorEstudiante
                            ControladorEstudiante controladorEstudiante = new ControladorEstudiante(colegio, codigo); //
                            MenuEstudiante menuEstudiante = new MenuEstudiante(controladorEstudiante); // Asume MenuEstudiante tiene constructor con ControladorEstudiante
                            menuEstudiante.setVisible(true);
                            menuEstudiante.setLocationRelativeTo(null);
                            break;*/
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Código o rol incorrecto.", "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un código numérico válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace(); 
            }
        });
    }
    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {                                            
   
    }                                           

    private void rolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                            
         
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal princ = new Principal();
                princ.setVisible(true);
                princ.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnContinue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> rolComboBox;
    private javax.swing.JLabel rolLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration                   
}

